name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: baekrang256/birdy:latest
      -
        name: Connect to EC2 container and build docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull baekrang256/birdy:latest
            sudo docker stop bot || true
            sudo docker rm bot || true
            sudo docker run -d \
            -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
            -e LAB_SERV_ID=${{ secrets.LAB_SERV_ID }} \
            --name bot baekrang256/birdy:latest
            sudo docker image prune -f
