# Prints difference of every incorrectly formatted file, and fail if there is any.
# Code acquired from : https://github.com/axel-op/googlejavaformat-action

name: "Format"

on: [ push, pull_request ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--replace"
          skipCommit: true
      - name: Print diffs
        run: git --no-pager diff --exit-code
